name: Dispatched
on:
  workflow_dispatch:
    inputs:
      ticket-id:
        required: true
        description: "チケットID"
      base-branch:
        required: true
        description: "ベースブランチ"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ticket-id=${{ github.event.inputs.ticket-id }}"
          echo "base-branch${{ github.event.inputs.base-branch }}"
          echo "base-branch${{ github.head_ref }}"
