name: Dispatched
on:
  workflow_dispatch:
    inputs:
      backend-branch:
        required: true
        description: "バックエンドの対応ブランチ"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "backend-branch=${{ github.event.inputs.backend-branch }}"
          echo "head_ref=${{ github.head_ref }}"
          if [ "${{ github.event_name }}"  == 'workflow_dispatch' ]; then
            echo "github.event_name == 'workflow_dispatch'"
          else
            echo "github.event_name != 'workflow_dispatch'"
          fi
